title: Markman's DEV blog
author: JaeJun.Lee
email: markman0510@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
# social links
github_username:  cooco119

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
